### ISSUE TITLE
Ship list export

### ISSUE THREAD

**Issue by oakenhold** [KCV-Localisation/KanColleViewer#66]
Hi, are there any plans to implement a ship list export function to complement the other logging functions that you already have?

**Comment by Yuubari** [comment]
I'm not sure how is ship list related to “logging”, care to elaborate?

It should be relatively simple to make a plug-in that would output a CSV listing of ships, though.

**Comment by menghon** [comment]
My apologies, your suggestion was exactly what I thought of. Basically, if all the details within "Ship List" button can be exported to CSV, that'll be very much appreciated.

**Comment by Yuubari** [comment]
You could probably write a plug-in that would do just that?..

**Comment by menghon** [comment]
Not too familiar with that though, just checking in to see if you'll be able to add it in your to-do list. Cheers

**Comment by gakada** [comment]
Or you can have a menu with Export -> CSV in Ship Roster that opens Save As dialog, then loop over ShipCatalogWindowViewModel.Ships and save to a given file, so that all filters get applied.

**Comment by Yuubari** [comment]
I'll think about it but it's definitely not a priority.

**Comment by menghon** [comment]
Much appreciated!
